require_relative("../models/category.rb")
require_relative("../models/merchant.rb")
require_relative("../models/transaction.rb")

category1 = Category.create({"name" => "food"})
category2 = Category.create({"name" => "drink"})
category3 = Category.create({"name" => "entertainment"})
category4 = Category.create({"name" => "finance"})
category5 = Category.create({"name" => "homeware"})
category6 = Category.create({"name" => "electronics"})
category7 = Category.create({"name" => "toys and games"})

merchant1 = Merchant.create({"name" => "tesco"})
merchant2 = Merchant.create({"name" => "royal bank of Scotland"})
merchant3 = Merchant.create({"name" => "currys"})
merchant4 = Merchant.create({"name" => "wetherspoons"})
merchant5 = Merchant.create({"name" => "cineworld"})
merchant6 = Merchant.create({"name" => "apple inc"})
merchant7 = Merchant.create({"name" => "google play store"})

transaction1 = Transaction.create({"description" => "i bought some food at tesco for a tenner, but that should be obvious", "amount" => 10.00, "merchant_id" => 1, "category_id" => 1})#, "transaction_date" => Time.new(2016, 01, 02)})
transaction2 = Transaction.create({"description" => "i bought a round at wetherspoons, it cost twenty quid, but that should be obvious", "amount" => 20.00, "merchant_id" => 4, "category_id" => 2})#, "transaction_date" => Time.new(2016, 01, 02)})
transaction3 = Transaction.create({"description" => "i bought an ipod charger at an apple store, 40 fuckin quid!? Bloody chancers. But that should be obvious", "amount" => 40.00, "merchant_id" => 6, "category_id" => 6})#, "transaction_date" => Time.new(2016, 01, 06)})
transaction4 = Transaction.create({"description" => "i bought two tickets to a 3D movie, popcorn and drinks. 30 quid? I bet that shit costs them 30p! But that should be obvious", "amount" => 30.00, "merchant_id" => 1, "category_id" => 3})#, "transaction_date" => Time.new(2016, 01, 02)})
transaction5 = Transaction.create({"description" => "i bought a case for my phone at currys, samsung are as bad as apple! but that should be obvious", "amount" => 60.00, "merchant_id" => 3, "category_id" => 6})#, "transaction_date" => Time.new(2016, 02, 12)})
transaction6 = Transaction.create({"description" => "i bought some EA games for my phone, wow, £50? This is why I need this app, but that should be obvious", "amount" => 50.00, "merchant_id" => 7, "category_id" => 7})#, "transaction_date" => Time.new(2016, 02, 11)})
transaction7 = Transaction.create({"description" => "i transered my flatmate 70 pounds for the energy bill, I hope that ugly Hydro stadium is worth it, pricks. But that should be obvious", "amount" => 70.00, "merchant_id" => 2, "category_id" => 4})#, "transaction_date" => Time.new(2016, 02, 11)})
transaction8 = Transaction.create({"description" => "i spent EIGHTY POUNDS in tesco to stock up on booze for the party this weekend, but that should be obvious", "amount" => 80.00, "merchant_id" => 1, "category_id" => 2})#, "transaction_date" => Time.new(2016, 02, 10)})

